name: On Push/Pull Request Smoke Testing

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Build Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
        
      - name: Prep Environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Test for 100% Coverage
        run: |
          pytest --cov=app --cov-fail-under=100
